# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: (c) 2022, Michael Herwig <contact@michael-herwig.de>

name: "Cppcheck Upload"
description: "GitHub Actions Check for Cppcheck .plist files."
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - --path=${{ inputs.path }}
    - --token=${{ inputs.github-token }}
inputs:
  path:
    description: Directory containing .plist files to upload.
    required: true
    default: ${{ github.workspace }}
  github-token:
    description: GitHub Access Token
    required: true
    default: ${{ github.token }}
